/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import startTextModel from "/src/assets/models/StartTextModel.glb?url"


type GLTFResult = GLTF & {
  nodes: {
    ResetTextModel: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function StartTextModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(startTextModel) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ResetTextModel.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload(startTextModel);
