// export const voiture:string = "src/assets/models/voiture.glb"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import voiture from "/src/assets/models/voiture.glb?url"

type GLTFResult = GLTF & {
  nodes: {
    Pick_Up_3D_Illustration001: THREE.Mesh;
  };
  materials: {
    ["Pick Up 3D Illustration"]: THREE.MeshStandardMaterial;
  };
};

export function VoitureModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(voiture) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pick_Up_3D_Illustration001.geometry}
        material={materials["Pick Up 3D Illustration"]}
        scale={0.22}
      />
    </group>
  );
}

useGLTF.preload(voiture);
